#' Cloud Firestore API Objects
#' Accesses the NoSQL document database built for automatic scaling, high performance, and ease of application development.
#'
#' Auto-generated code by googleAuthR::gar_create_api_objects
#'  at 2021-08-19 09:15:03
#' filename: /home/juha/workspace/autoGoogleAPI//googlefirestorev1.auto/R/firestore_objects.R
#' api_json: api_json
#'
#' Objects for use by the functions created by googleAuthR::gar_create_api_skeleton

#' Write Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A write on a document.
#'
#' @param transform Applies a transformation to a document
#' @param updateTransforms The transforms to perform after update
#' @param delete A document name to delete
#' @param currentDocument An optional precondition on the document
#' @param updateMask The fields to update in this write
#' @param update A document to write
#'
#' @return Write object
#'
#' @family Write functions
#' @export
Write <- function(transform = NULL, updateTransforms = NULL, delete = NULL, currentDocument = NULL,
    updateMask = NULL, update = NULL) {
    structure(list(transform = transform, updateTransforms = updateTransforms, delete = delete,
        currentDocument = currentDocument, updateMask = updateMask, update = update),
        class = c("gar_Write", "list"))
}

#' GoogleFirestoreAdminV1IndexOperationMetadata Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Metadata for google.longrunning.Operation results from FirestoreAdmin.CreateIndex.
#'
#' @param progressBytes The progress, in bytes, of this operation
#' @param progressDocuments The progress, in documents, of this operation
#' @param state The state of the operation
#' @param endTime The time this operation completed
#' @param index The index resource that this operation is acting on
#' @param startTime The time this operation started
#'
#' @return GoogleFirestoreAdminV1IndexOperationMetadata object
#'
#' @family GoogleFirestoreAdminV1IndexOperationMetadata functions
#' @export
GoogleFirestoreAdminV1IndexOperationMetadata <- function(progressBytes = NULL, progressDocuments = NULL,
    state = NULL, endTime = NULL, index = NULL, startTime = NULL) {
    structure(list(progressBytes = progressBytes, progressDocuments = progressDocuments,
        state = state, endTime = endTime, index = index, startTime = startTime),
        class = c("gar_GoogleFirestoreAdminV1IndexOperationMetadata", "list"))
}

#' GoogleFirestoreAdminV1FieldOperationMetadata Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Metadata for google.longrunning.Operation results from FirestoreAdmin.UpdateField.
#'
#' @param startTime The time this operation started
#' @param indexConfigDeltas A list of IndexConfigDelta, which describe the intent of this operation
#' @param progressBytes The progress, in bytes, of this operation
#' @param endTime The time this operation completed
#' @param field The field resource that this operation is acting on
#' @param progressDocuments The progress, in documents, of this operation
#' @param state The state of the operation
#'
#' @return GoogleFirestoreAdminV1FieldOperationMetadata object
#'
#' @family GoogleFirestoreAdminV1FieldOperationMetadata functions
#' @export
GoogleFirestoreAdminV1FieldOperationMetadata <- function(startTime = NULL, indexConfigDeltas = NULL,
    progressBytes = NULL, endTime = NULL, field = NULL, progressDocuments = NULL,
    state = NULL) {
    structure(list(startTime = startTime, indexConfigDeltas = indexConfigDeltas,
        progressBytes = progressBytes, endTime = endTime, field = field, progressDocuments = progressDocuments,
        state = state), class = c("gar_GoogleFirestoreAdminV1FieldOperationMetadata",
        "list"))
}

#' FieldTransform Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A transformation of a field of the document.
#'
#' @param setToServerValue Sets the field to the given server value
#' @param minimum Sets the field to the minimum of its current value and the given value
#' @param removeAllFromArray Remove all of the given elements from the array in the field
#' @param increment Adds the given value to the field's current value
#' @param fieldPath The path of the field
#' @param appendMissingElements Append the given elements in order if they are not already present in the current field value
#' @param maximum Sets the field to the maximum of its current value and the given value
#'
#' @return FieldTransform object
#'
#' @family FieldTransform functions
#' @export
FieldTransform <- function(setToServerValue = NULL, minimum = NULL, removeAllFromArray = NULL,
    increment = NULL, fieldPath = NULL, appendMissingElements = NULL, maximum = NULL) {
    structure(list(setToServerValue = setToServerValue, minimum = minimum, removeAllFromArray = removeAllFromArray,
        increment = increment, fieldPath = fieldPath, appendMissingElements = appendMissingElements,
        maximum = maximum), class = c("gar_FieldTransform", "list"))
}

#' ListenResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for Firestore.Listen.
#'
#' @param documentRemove A Document has been removed from a target (because it is no longer relevant to that target)
#' @param documentDelete A Document has been deleted
#' @param targetChange Targets have changed
#' @param documentChange A Document has changed
#' @param filter A filter to apply to the set of documents previously returned for the given target
#'
#' @return ListenResponse object
#'
#' @family ListenResponse functions
#' @export
ListenResponse <- function(documentRemove = NULL, documentDelete = NULL, targetChange = NULL,
    documentChange = NULL, filter = NULL) {
    structure(list(documentRemove = documentRemove, documentDelete = documentDelete,
        targetChange = targetChange, documentChange = documentChange, filter = filter),
        class = c("gar_ListenResponse", "list"))
}

#' ListCollectionIdsRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.ListCollectionIds.
#'
#' @param pageToken A page token
#' @param pageSize The maximum number of results to return
#'
#' @return ListCollectionIdsRequest object
#'
#' @family ListCollectionIdsRequest functions
#' @export
ListCollectionIdsRequest <- function(pageToken = NULL, pageSize = NULL) {
    structure(list(pageToken = pageToken, pageSize = pageSize), class = c("gar_ListCollectionIdsRequest",
        "list"))
}

#' ListCollectionIdsResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response from Firestore.ListCollectionIds.
#'
#' @param nextPageToken A page token that may be used to continue the list
#' @param collectionIds The collection ids
#'
#' @return ListCollectionIdsResponse object
#'
#' @family ListCollectionIdsResponse functions
#' @export
ListCollectionIdsResponse <- function(nextPageToken = NULL, collectionIds = NULL) {
    structure(list(nextPageToken = nextPageToken, collectionIds = collectionIds),
        class = c("gar_ListCollectionIdsResponse", "list"))
}

#' BatchGetDocumentsResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The streamed response for Firestore.BatchGetDocuments.
#'
#' @param missing A document name that was requested but does not exist
#' @param transaction The transaction that was started as part of this request
#' @param readTime The time at which the document was read
#' @param found A document that was requested
#'
#' @return BatchGetDocumentsResponse object
#'
#' @family BatchGetDocumentsResponse functions
#' @export
BatchGetDocumentsResponse <- function(missing = NULL, transaction = NULL, readTime = NULL,
    found = NULL) {
    structure(list(missing = missing, transaction = transaction, readTime = readTime,
        found = found), class = c("gar_BatchGetDocumentsResponse", "list"))
}

#' TransactionOptions Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Options for creating a new transaction.
#'
#' @param readOnly The transaction can only be used for read operations
#' @param readWrite The transaction can be used for both read and write operations
#'
#' @return TransactionOptions object
#'
#' @family TransactionOptions functions
#' @export
TransactionOptions <- function(readOnly = NULL, readWrite = NULL) {
    structure(list(readOnly = readOnly, readWrite = readWrite), class = c("gar_TransactionOptions",
        "list"))
}

#' GoogleFirestoreAdminV1ListFieldsResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for FirestoreAdmin.ListFields.
#'
#' @param fields The requested fields
#' @param nextPageToken A page token that may be used to request another page of results
#'
#' @return GoogleFirestoreAdminV1ListFieldsResponse object
#'
#' @family GoogleFirestoreAdminV1ListFieldsResponse functions
#' @export
GoogleFirestoreAdminV1ListFieldsResponse <- function(fields = NULL, nextPageToken = NULL) {
    structure(list(fields = fields, nextPageToken = nextPageToken), class = c("gar_GoogleFirestoreAdminV1ListFieldsResponse",
        "list"))
}

#' MapValue Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A map value.
#'
#' @param fields The map's fields. The map keys represent field names. Field names matching the regular expression `__.*__` are reserved. Reserved field names are forbidden except in certain documented contexts. The map keys, represented as UTF-8, must not exceed 1,500 bytes and cannot be empty.
#'
#' @return MapValue object
#'
#' @family MapValue functions
#' @export
MapValue <- function(fields = NULL) {
    structure(list(fields = fields), class = c("gar_MapValue",
        "list"))
}

#' GoogleFirestoreAdminV1ExportDocumentsResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Returned in the google.longrunning.Operation response field.
#'
#' @param outputUriPrefix Location of the output files
#'
#' @return GoogleFirestoreAdminV1ExportDocumentsResponse object
#'
#' @family GoogleFirestoreAdminV1ExportDocumentsResponse functions
#' @export
GoogleFirestoreAdminV1ExportDocumentsResponse <- function(outputUriPrefix = NULL) {
    structure(list(outputUriPrefix = outputUriPrefix), class = c("gar_GoogleFirestoreAdminV1ExportDocumentsResponse",
        "list"))
}

#' FieldFilter Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A filter on a specific field.
#'
#' @param value The value to compare to
#' @param field The field to filter by
#' @param op The operator to filter by
#'
#' @return FieldFilter object
#'
#' @family FieldFilter functions
#' @export
FieldFilter <- function(value = NULL, field = NULL, op = NULL) {
    structure(list(value = value, field = field, op = op), class = c("gar_FieldFilter",
        "list"))
}

#' DocumentRemove Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A Document has been removed from the view of the targets. Sent if the document is no longer relevant to a target and is out of view. Can be sent instead of a DocumentDelete or a DocumentChange if the server can not send the new value of the document. Multiple DocumentRemove messages may be returned for the same logical write or delete, if multiple targets are affected.
#'
#' @param removedTargetIds A set of target IDs for targets that previously matched this document
#' @param document The resource name of the Document that has gone out of view
#' @param readTime The read timestamp at which the remove was observed
#'
#' @return DocumentRemove object
#'
#' @family DocumentRemove functions
#' @export
DocumentRemove <- function(removedTargetIds = NULL, document = NULL, readTime = NULL) {
    structure(list(removedTargetIds = removedTargetIds, document = document, readTime = readTime),
        class = c("gar_DocumentRemove", "list"))
}

#' CollectionSelector Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A selection of a collection, such as `messages as m1`.
#'
#' @param collectionId The collection ID
#' @param allDescendants When false, selects only collections that are immediate children of the `parent` specified in the containing `RunQueryRequest`
#'
#' @return CollectionSelector object
#'
#' @family CollectionSelector functions
#' @export
CollectionSelector <- function(collectionId = NULL, allDescendants = NULL) {
    structure(list(collectionId = collectionId, allDescendants = allDescendants),
        class = c("gar_CollectionSelector", "list"))
}

#' ReadOnly Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Options for a transaction that can only be used to read documents.
#'
#' @param readTime Reads documents at the given time
#'
#' @return ReadOnly object
#'
#' @family ReadOnly functions
#' @export
ReadOnly <- function(readTime = NULL) {
    structure(list(readTime = readTime), class = c("gar_ReadOnly", "list"))
}

#' WriteRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.Write. The first request creates a stream, or resumes an existing one from a token. When creating a new stream, the server replies with a response containing only an ID and a token, to use in the next request. When resuming a stream, the server first streams any responses later than the given token, then a response containing only an up-to-date token, to use in the next request.
#'
#' @param writes The writes to apply
#' @param streamToken A stream token that was previously sent by the server
#' @param labels Labels associated with this write request
#' @param streamId The ID of the write stream to resume
#'
#' @return WriteRequest object
#'
#' @family WriteRequest functions
#' @export
WriteRequest <- function(writes = NULL, streamToken = NULL,
    labels = NULL, streamId = NULL) {
    structure(list(writes = writes, streamToken = streamToken,
        labels = labels, streamId = streamId), class = c("gar_WriteRequest", "list"))
}

#' Precondition Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A precondition on a document, used for conditional operations.
#'
#' @param updateTime When set, the target document must exist and have been last updated at that time
#' @param exists When set to `true`, the target document must exist
#'
#' @return Precondition object
#'
#' @family Precondition functions
#' @export
Precondition <- function(updateTime = NULL, exists = NULL) {
    structure(list(updateTime = updateTime, exists = exists), class = c("gar_Precondition",
        "list"))
}

#' PartitionQueryResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for Firestore.PartitionQuery.
#'
#' @param partitions Partition results
#' @param nextPageToken A page token that may be used to request an additional set of results, up to the number specified by `partition_count` in the PartitionQuery request
#'
#' @return PartitionQueryResponse object
#'
#' @family PartitionQueryResponse functions
#' @export
PartitionQueryResponse <- function(partitions = NULL, nextPageToken = NULL) {
    structure(list(partitions = partitions, nextPageToken = nextPageToken), class = c("gar_PartitionQueryResponse",
        "list"))
}

#' GoogleFirestoreAdminV1IndexField Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A field in an index. The field_path describes which field is indexed, the value_mode describes how the field value is indexed.
#'
#' @param arrayConfig Indicates that this field supports operations on `array_value`s
#' @param order Indicates that this field supports ordering by the specified order or comparing using =, !=, <, <=, >, >=
#' @param fieldPath Can be __name__
#'
#' @return GoogleFirestoreAdminV1IndexField object
#'
#' @family GoogleFirestoreAdminV1IndexField functions
#' @export
GoogleFirestoreAdminV1IndexField <- function(arrayConfig = NULL, order = NULL, fieldPath = NULL) {
    structure(list(arrayConfig = arrayConfig, order = order, fieldPath = fieldPath),
        class = c("gar_GoogleFirestoreAdminV1IndexField", "list"))
}

#' FieldReference Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A reference to a field, such as `max(messages.time) as max_time`.
#'
#' @param fieldPath No description
#'
#' @return FieldReference object
#'
#' @family FieldReference functions
#' @export
FieldReference <- function(fieldPath = NULL) {
    structure(list(fieldPath = fieldPath), class = c("gar_FieldReference", "list"))
}

#' DocumentsTarget Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A target specified by a set of documents names.
#'
#' @param documents The names of the documents to retrieve
#'
#' @return DocumentsTarget object
#'
#' @family DocumentsTarget functions
#' @export
DocumentsTarget <- function(documents = NULL) {
    structure(list(documents = documents), class = c("gar_DocumentsTarget", "list"))
}

#' BatchGetDocumentsRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.BatchGetDocuments.
#'
#' @param newTransaction Starts a new transaction and reads the documents
#' @param documents The names of the documents to retrieve
#' @param readTime Reads documents as they were at the given time
#' @param mask The fields to return
#' @param transaction Reads documents in a transaction
#'
#' @return BatchGetDocumentsRequest object
#'
#' @family BatchGetDocumentsRequest functions
#' @export
BatchGetDocumentsRequest <- function(newTransaction = NULL, documents = NULL, readTime = NULL,
    mask = NULL, transaction = NULL) {
    structure(list(newTransaction = newTransaction, documents = documents, readTime = readTime,
        mask = mask, transaction = transaction), class = c("gar_BatchGetDocumentsRequest",
        "list"))
}

#' CommitResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for Firestore.Commit.
#'
#' @param writeResults The result of applying the writes
#' @param commitTime The time at which the commit occurred
#'
#' @return CommitResponse object
#'
#' @family CommitResponse functions
#' @export
CommitResponse <- function(writeResults = NULL, commitTime = NULL) {
    structure(list(writeResults = writeResults, commitTime = commitTime), class = c("gar_CommitResponse",
        "list"))
}

#' GoogleFirestoreAdminV1Field Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Represents a single field in the database. Fields are grouped by their 'Collection Group', which represent all collections in the database with the same id.
#'
#' @param indexConfig The index configuration for this field
#' @param name Required
#'
#' @return GoogleFirestoreAdminV1Field object
#'
#' @family GoogleFirestoreAdminV1Field functions
#' @export
GoogleFirestoreAdminV1Field <- function(indexConfig = NULL, name = NULL) {
    structure(list(indexConfig = indexConfig, name = name), class = c("gar_GoogleFirestoreAdminV1Field",
        "list"))
}

#' GoogleFirestoreAdminV1ExportDocumentsRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for FirestoreAdmin.ExportDocuments.
#'
#' @param outputUriPrefix The output URI
#' @param collectionIds Which collection ids to export
#'
#' @return GoogleFirestoreAdminV1ExportDocumentsRequest object
#'
#' @family GoogleFirestoreAdminV1ExportDocumentsRequest functions
#' @export
GoogleFirestoreAdminV1ExportDocumentsRequest <- function(outputUriPrefix = NULL,
    collectionIds = NULL) {
    structure(list(outputUriPrefix = outputUriPrefix, collectionIds = collectionIds),
        class = c("gar_GoogleFirestoreAdminV1ExportDocumentsRequest", "list"))
}

#' UnaryFilter Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A filter with a single operand.
#'
#' @param op The unary operator to apply
#' @param field The field to which to apply the operator
#'
#' @return UnaryFilter object
#'
#' @family UnaryFilter functions
#' @export
UnaryFilter <- function(op = NULL, field = NULL) {
    structure(list(op = op, field = field), class = c("gar_UnaryFilter", "list"))
}

#' Empty Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. For instance: service Foo { rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty); } The JSON representation for `Empty` is empty JSON object `{}`.
#'
#'
#'
#' @return Empty object
#'
#' @family Empty functions
#' @export
Empty <- function() {
    list()
}

#' Document Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A Firestore document. Must not exceed 1 MiB - 4 bytes.
#'
#' @param name The resource name of the document, for example `projects/{project_id}/databases/{database_id}/documents/{document_path}`
#' @param createTime Output only
#' @param updateTime Output only
#' @param fields The document's fields. The map keys represent field names. A simple field name contains only characters `a` to `z`, `A` to `Z`, `0` to `9`, or `_`, and must not start with `0` to `9`. For example, `foo_bar_17`. Field names matching the regular expression `__.*__` are reserved. Reserved field names are forbidden except in certain documented contexts. The map keys, represented as UTF-8, must not exceed 1,500 bytes and cannot be empty. Field paths may be used in other contexts to refer to structured fields defined here. For `map_value`, the field path is represented by the simple or quoted field names of the containing fields, delimited by `.`. For example, the structured field `'foo' : { map_value: { 'x&y' : { string_value: 'hello' }}}` would be represented by the field path `foo.x&y`. Within a field path, a quoted field name starts and ends with `` ` `` and may contain any character. Some characters, including `` ` ``, must be escaped using a `\`. For example, `` `x&y` `` represents `x&y` and `` `bak\`tik` `` represents `` bak`tik ``.
#'
#' @return Document object
#'
#' @family Document functions
#' @export
Document <- function(name = NULL, createTime = NULL, updateTime = NULL, fields = NULL) {
  structure(list(name = name, createTime = createTime,
                 updateTime = updateTime, fields = fields
                 ), class = c("gar_Document", "list"))
}

#' BeginTransactionRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.BeginTransaction.
#'
#' @param options The options for the transaction
#'
#' @return BeginTransactionRequest object
#'
#' @family BeginTransactionRequest functions
#' @export
BeginTransactionRequest <- function(options = NULL) {
    structure(list(options = options), class = c("gar_BeginTransactionRequest", "list"))
}

#' Filter Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A filter.
#'
#' @param unaryFilter A filter that takes exactly one argument
#' @param compositeFilter A composite filter
#' @param fieldFilter A filter on a document field
#'
#' @return Filter object
#'
#' @family Filter functions
#' @export
Filter <- function(unaryFilter = NULL, compositeFilter = NULL, fieldFilter = NULL) {
    structure(list(unaryFilter = unaryFilter, compositeFilter = compositeFilter,
        fieldFilter = fieldFilter), class = c("gar_Filter", "list"))
}

#' CompositeFilter Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A filter that merges multiple other filters using the given operator.
#'
#' @param filters The list of filters to combine
#' @param op The operator for combining multiple filters
#'
#' @return CompositeFilter object
#'
#' @family CompositeFilter functions
#' @export
CompositeFilter <- function(filters = NULL, op = NULL) {
    structure(list(filters = filters, op = op), class = c("gar_CompositeFilter",
        "list"))
}

#' RollbackRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.Rollback.
#'
#' @param transaction Required
#'
#' @return RollbackRequest object
#'
#' @family RollbackRequest functions
#' @export
RollbackRequest <- function(transaction = NULL) {
    structure(list(transaction = transaction), class = c("gar_RollbackRequest", "list"))
}

#' Projection Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The projection of document's fields to return.
#'
#' @param fields The fields to return
#'
#' @return Projection object
#'
#' @family Projection functions
#' @export
Projection <- function(fields = NULL) {
    structure(list(fields = fields), class = c("gar_Projection", "list"))
}

#' Order Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' An order on a field.
#'
#' @param field The field to order by
#' @param direction The direction to order by
#'
#' @return Order object
#'
#' @family Order functions
#' @export
Order <- function(field = NULL, direction = NULL) {
    structure(list(field = field, direction = direction), class = c("gar_Order",
        "list"))
}

#' ListDocumentsResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for Firestore.ListDocuments.
#'
#' @param nextPageToken The next page token
#' @param documents The Documents found
#'
#' @return ListDocumentsResponse object
#'
#' @family ListDocumentsResponse functions
#' @export
ListDocumentsResponse <- function(nextPageToken = NULL, documents = NULL) {
    structure(list(nextPageToken = nextPageToken, documents = documents), class = c("gar_ListDocumentsResponse",
        "list"))
}

#' RunQueryResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for Firestore.RunQuery.
#'
#' @param transaction The transaction that was started as part of this request
#' @param skippedResults The number of results that have been skipped due to an offset between the last response and the current response
#' @param readTime The time at which the document was read
#' @param document A query result
#'
#' @return RunQueryResponse object
#'
#' @family RunQueryResponse functions
#' @export
RunQueryResponse <- function(transaction = NULL, skippedResults = NULL, readTime = NULL,
    document = NULL) {
    structure(list(transaction = transaction, skippedResults = skippedResults, readTime = readTime,
        document = document), class = c("gar_RunQueryResponse", "list"))
}

#' Status Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
#'
#' @param details A list of messages that carry the error details
#' @param message A developer-facing error message, which should be in English
#' @param code The status code, which should be an enum value of google
#'
#' @return Status object
#'
#' @family Status functions
#' @export
Status <- function(details = NULL, message = NULL, code = NULL) {
    structure(list(details = details, message = message, code = code), class = c("gar_Status",
        "list"))
}

#' WriteResult Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The result of applying a write.
#'
#' @param updateTime The last update time of the document after applying the write
#' @param transformResults The results of applying each DocumentTransform
#'
#' @return WriteResult object
#'
#' @family WriteResult functions
#' @export
WriteResult <- function(updateTime = NULL, transformResults = NULL) {
    structure(list(updateTime = updateTime, transformResults = transformResults),
        class = c("gar_WriteResult", "list"))
}

#' CommitRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.Commit.
#'
#' @param transaction If set, applies all writes in this transaction, and commits it
#' @param writes The writes to apply
#'
#' @return CommitRequest object
#'
#' @family CommitRequest functions
#' @export
CommitRequest <- function(transaction = NULL, writes = NULL) {
    structure(list(transaction = transaction, writes = writes), class = c("gar_CommitRequest",
        "list"))
}

#' GoogleFirestoreAdminV1LocationMetadata Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The metadata message for google.cloud.location.Location.metadata.
#'
#'
#'
#' @return GoogleFirestoreAdminV1LocationMetadata object
#'
#' @family GoogleFirestoreAdminV1LocationMetadata functions
#' @export
GoogleFirestoreAdminV1LocationMetadata <- function() {
    list()
}

#' ListenRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A request for Firestore.Listen
#'
#' @param labels Labels associated with this target change
#' @param removeTarget The ID of a target to remove from this stream
#' @param addTarget A target to add to this stream
#'
#' @return ListenRequest object
#'
#' @family ListenRequest functions
#' @export
ListenRequest <- function(labels = NULL, removeTarget = NULL,
    addTarget = NULL) {
    structure(list(labels = labels,
        removeTarget = removeTarget, addTarget = addTarget), class = c("gar_ListenRequest",
        "list"))
}

#' GoogleFirestoreAdminV1Progress Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Describes the progress of the operation. Unit of work is generic and must be interpreted based on where Progress is used.
#'
#' @param completedWork The amount of work completed
#' @param estimatedWork The amount of work estimated
#'
#' @return GoogleFirestoreAdminV1Progress object
#'
#' @family GoogleFirestoreAdminV1Progress functions
#' @export
GoogleFirestoreAdminV1Progress <- function(completedWork = NULL, estimatedWork = NULL) {
    structure(list(completedWork = completedWork, estimatedWork = estimatedWork),
        class = c("gar_GoogleFirestoreAdminV1Progress", "list"))
}

#' GoogleLongrunningListOperationsResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response message for Operations.ListOperations.
#'
#' @param nextPageToken The standard List next-page token
#' @param operations A list of operations that matches the specified filter in the request
#'
#' @return GoogleLongrunningListOperationsResponse object
#'
#' @family GoogleLongrunningListOperationsResponse functions
#' @export
GoogleLongrunningListOperationsResponse <- function(nextPageToken = NULL, operations = NULL) {
    structure(list(nextPageToken = nextPageToken, operations = operations), class = c("gar_GoogleLongrunningListOperationsResponse",
        "list"))
}

#' QueryTarget Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A target specified by a query.
#'
#' @param structuredQuery A structured query
#' @param parent The parent resource name
#'
#' @return QueryTarget object
#'
#' @family QueryTarget functions
#' @export
QueryTarget <- function(structuredQuery = NULL, parent = NULL) {
    structure(list(structuredQuery = structuredQuery, parent = parent), class = c("gar_QueryTarget",
        "list"))
}

#' GoogleFirestoreAdminV1ExportDocumentsMetadata Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Metadata for google.longrunning.Operation results from FirestoreAdmin.ExportDocuments.
#'
#' @param progressBytes The progress, in bytes, of this operation
#' @param operationState The state of the export operation
#' @param startTime The time this operation started
#' @param progressDocuments The progress, in documents, of this operation
#' @param endTime The time this operation completed
#' @param collectionIds Which collection ids are being exported
#' @param outputUriPrefix Where the entities are being exported to
#'
#' @return GoogleFirestoreAdminV1ExportDocumentsMetadata object
#'
#' @family GoogleFirestoreAdminV1ExportDocumentsMetadata functions
#' @export
GoogleFirestoreAdminV1ExportDocumentsMetadata <- function(progressBytes = NULL, operationState = NULL,
    startTime = NULL, progressDocuments = NULL, endTime = NULL, collectionIds = NULL,
    outputUriPrefix = NULL) {
    structure(list(progressBytes = progressBytes, operationState = operationState,
        startTime = startTime, progressDocuments = progressDocuments, endTime = endTime,
        collectionIds = collectionIds, outputUriPrefix = outputUriPrefix), class = c("gar_GoogleFirestoreAdminV1ExportDocumentsMetadata",
        "list"))
}

#' GoogleLongrunningCancelOperationRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request message for Operations.CancelOperation.
#'
#'
#'
#' @return GoogleLongrunningCancelOperationRequest object
#'
#' @family GoogleLongrunningCancelOperationRequest functions
#' @export
GoogleLongrunningCancelOperationRequest <- function() {
    list()
}

#' GoogleFirestoreAdminV1ImportDocumentsMetadata Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Metadata for google.longrunning.Operation results from FirestoreAdmin.ImportDocuments.
#'
#' @param endTime The time this operation completed
#' @param collectionIds Which collection ids are being imported
#' @param progressDocuments The progress, in documents, of this operation
#' @param progressBytes The progress, in bytes, of this operation
#' @param operationState The state of the import operation
#' @param startTime The time this operation started
#' @param inputUriPrefix The location of the documents being imported
#'
#' @return GoogleFirestoreAdminV1ImportDocumentsMetadata object
#'
#' @family GoogleFirestoreAdminV1ImportDocumentsMetadata functions
#' @export
GoogleFirestoreAdminV1ImportDocumentsMetadata <- function(endTime = NULL, collectionIds = NULL,
    progressDocuments = NULL, progressBytes = NULL, operationState = NULL, startTime = NULL,
    inputUriPrefix = NULL) {
    structure(list(endTime = endTime, collectionIds = collectionIds, progressDocuments = progressDocuments,
        progressBytes = progressBytes, operationState = operationState, startTime = startTime,
        inputUriPrefix = inputUriPrefix), class = c("gar_GoogleFirestoreAdminV1ImportDocumentsMetadata",
        "list"))
}

#' TargetChange Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Targets being watched have changed.
#'
#' @param targetChangeType The type of change that occurred
#' @param cause The error that resulted in this change, if applicable
#' @param targetIds The target IDs of targets that have changed
#' @param readTime The consistent `read_time` for the given `target_ids` (omitted when the target_ids are not at a consistent snapshot)
#' @param resumeToken A token that can be used to resume the stream for the given `target_ids`, or all targets if `target_ids` is empty
#'
#' @return TargetChange object
#'
#' @family TargetChange functions
#' @export
TargetChange <- function(targetChangeType = NULL, cause = NULL, targetIds = NULL,
    readTime = NULL, resumeToken = NULL) {
    structure(list(targetChangeType = targetChangeType, cause = cause, targetIds = targetIds,
        readTime = readTime, resumeToken = resumeToken), class = c("gar_TargetChange",
        "list"))
}

#' GoogleFirestoreAdminV1Index Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Cloud Firestore indexes enable simple and complex queries against documents in a database.
#'
#' @param state Output only
#' @param queryScope Indexes with a collection query scope specified allow queries against a collection that is the child of a specific document, specified at query time, and that has the same collection id
#' @param fields The fields supported by this index
#' @param name Output only
#'
#' @return GoogleFirestoreAdminV1Index object
#'
#' @family GoogleFirestoreAdminV1Index functions
#' @export
GoogleFirestoreAdminV1Index <- function(state = NULL, queryScope = NULL, fields = NULL,
    name = NULL) {
    structure(list(state = state, queryScope = queryScope, fields = fields, name = name),
        class = c("gar_GoogleFirestoreAdminV1Index", "list"))
}

#' GoogleFirestoreAdminV1IndexConfigDelta Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Information about an index configuration change.
#'
#' @param changeType Specifies how the index is changing
#' @param index The index being changed
#'
#' @return GoogleFirestoreAdminV1IndexConfigDelta object
#'
#' @family GoogleFirestoreAdminV1IndexConfigDelta functions
#' @export
GoogleFirestoreAdminV1IndexConfigDelta <- function(changeType = NULL, index = NULL) {
    structure(list(changeType = changeType, index = index), class = c("gar_GoogleFirestoreAdminV1IndexConfigDelta",
        "list"))
}

#' StructuredQuery Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A Firestore query.
#'
#' @param select The projection to return
#' @param from The collections to query
#' @param where The filter to apply
#' @param orderBy The order to apply to the query results
#' @param startAt A starting point for the query results
#' @param endAt A end point for the query results
#' @param offset The number of results to skip
#' @param limit The maximum number of results to return
#'
#' @return StructuredQuery object
#'
#' @family StructuredQuery functions
#' @export
StructuredQuery <- function(select = NULL, from = NULL, where = NULL, orderBy = NULL, startAt = NULL, endAt = NULL,
                            offset = NULL, limit = NULL) {
  structure(list(offset = offset, where = where, startAt = startAt, endAt = endAt,
                 limit = limit, from = from, orderBy = orderBy, select = select),
            class = c("gar_StructuredQuery", "list"))
}

#' GoogleFirestoreAdminV1ListIndexesResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for FirestoreAdmin.ListIndexes.
#'
#' @param indexes The requested indexes
#' @param nextPageToken A page token that may be used to request another page of results
#'
#' @return GoogleFirestoreAdminV1ListIndexesResponse object
#'
#' @family GoogleFirestoreAdminV1ListIndexesResponse functions
#' @export
GoogleFirestoreAdminV1ListIndexesResponse <- function(indexes = NULL, nextPageToken = NULL) {
    structure(list(indexes = indexes, nextPageToken = nextPageToken), class = c("gar_GoogleFirestoreAdminV1ListIndexesResponse",
        "list"))
}

#' ExistenceFilter Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A digest of all the documents that match a given target.
#'
#' @param targetId The target ID to which this filter applies
#' @param count The total count of documents that match target_id
#'
#' @return ExistenceFilter object
#'
#' @family ExistenceFilter functions
#' @export
ExistenceFilter <- function(targetId = NULL, count = NULL) {
    structure(list(targetId = targetId, count = count), class = c("gar_ExistenceFilter",
        "list"))
}

#' DocumentChange Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A Document has changed. May be the result of multiple writes, including deletes, that ultimately resulted in a new value for the Document. Multiple DocumentChange messages may be returned for the same logical change, if multiple targets are affected.
#'
#' @param targetIds A set of target IDs of targets that match this document
#' @param removedTargetIds A set of target IDs for targets that no longer match this document
#' @param document The new state of the Document
#'
#' @return DocumentChange object
#'
#' @family DocumentChange functions
#' @export
DocumentChange <- function(targetIds = NULL, removedTargetIds = NULL, document = NULL) {
    structure(list(targetIds = targetIds, removedTargetIds = removedTargetIds, document = document),
        class = c("gar_DocumentChange", "list"))
}

#' DocumentMask Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A set of field paths on a document. Used to restrict a get or update operation on a document to a subset of its fields. This is different from standard field masks, as this is always scoped to a Document, and takes in account the dynamic nature of Value.
#'
#' @param fieldPaths The list of field paths in the mask
#'
#' @return DocumentMask object
#'
#' @family DocumentMask functions
#' @export
DocumentMask <- function(fieldPaths = NULL) {
    structure(list(fieldPaths = fieldPaths), class = c("gar_DocumentMask", "list"))
}

#' Cursor Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A position in a query result set.
#'
#' @param values The values that represent a position, in the order they appear in the order by clause of a query
#' @param before If the position is just before or just after the given values, relative to the sort order defined by the query
#'
#' @return Cursor object
#'
#' @family Cursor functions
#' @export
Cursor <- function(values = NULL, before = NULL) {
    structure(list(values = values, before = before), class = c("gar_Cursor", "list"))
}

#' Location Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A resource that represents Google Cloud Platform location.
#'
#' @param labels Cross-service attributes for the location. For example {'cloud.googleapis.com/region': 'us-east1'}
#' @param metadata Service-specific metadata. For example the available capacity at the given location.
#' @param locationId The canonical id for this location
#' @param name Resource name for the location, which may vary between implementations
#' @param displayName The friendly name for this location, typically a nearby city name
#'
#' @return Location object
#'
#' @family Location functions
#' @export
Location <- function(labels = NULL,
    metadata = NULL, locationId = NULL, name = NULL, displayName = NULL) {
    structure(list(labels = labels, metadata = metadata, locationId = locationId, name = name,
                   displayName = displayName), class = c("gar_Location", "list"))
}

#' ArrayValue Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' An array value.
#'
#' @param values Values in the array
#'
#' @return ArrayValue object
#'
#' @family ArrayValue functions
#' @export
ArrayValue <- function(values = NULL) {
    structure(list(values = values), class = c("gar_ArrayValue", "list"))
}

#' GoogleFirestoreAdminV1IndexConfig Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The index configuration for this field.
#'
#' @param reverting Output only When true, the `Field`'s index configuration is in the process of being reverted
#' @param ancestorField Output only
#' @param usesAncestorConfig Output only
#' @param indexes The indexes supported for this field
#'
#' @return GoogleFirestoreAdminV1IndexConfig object
#'
#' @family GoogleFirestoreAdminV1IndexConfig functions
#' @export
GoogleFirestoreAdminV1IndexConfig <- function(reverting = NULL, ancestorField = NULL,
    usesAncestorConfig = NULL, indexes = NULL) {
    structure(list(reverting = reverting, ancestorField = ancestorField, usesAncestorConfig = usesAncestorConfig,
        indexes = indexes), class = c("gar_GoogleFirestoreAdminV1IndexConfig", "list"))
}

#' LatLng Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to represent degrees latitude and degrees longitude. Unless specified otherwise, this object must conform to the WGS84 standard. Values must be within normalized ranges.
#'
#' @param longitude The longitude in degrees
#' @param latitude The latitude in degrees
#'
#' @return LatLng object
#'
#' @family LatLng functions
#' @export
LatLng <- function(longitude = NULL, latitude = NULL) {
    structure(list(longitude = longitude, latitude = latitude), class = c("gar_LatLng",
        "list"))
}

#' Target Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A specification of a set of documents to listen to.
#'
#' @param resumeToken A resume token from a prior TargetChange for an identical target
#' @param targetId The target ID that identifies the target on the stream
#' @param once If the target should be removed once it is current and consistent
#' @param readTime Start listening after a specific `read_time`
#' @param query A target specified by a query
#' @param documents A target specified by a set of document names
#'
#' @return Target object
#'
#' @family Target functions
#' @export
Target <- function(resumeToken = NULL, targetId = NULL, once = NULL, readTime = NULL,
    query = NULL, documents = NULL) {
    structure(list(resumeToken = resumeToken, targetId = targetId, once = once, readTime = readTime,
        query = query, documents = documents), class = c("gar_Target", "list"))
}

#' BatchWriteResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response from Firestore.BatchWrite.
#'
#' @param status The status of applying the writes
#' @param writeResults The result of applying the writes
#'
#' @return BatchWriteResponse object
#'
#' @family BatchWriteResponse functions
#' @export
BatchWriteResponse <- function(status = NULL, writeResults = NULL) {
    structure(list(status = status, writeResults = writeResults), class = c("gar_BatchWriteResponse",
        "list"))
}

#' ListLocationsResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response message for Locations.ListLocations.
#'
#' @param nextPageToken The standard List next-page token
#' @param locations A list of locations that matches the specified filter in the request
#'
#' @return ListLocationsResponse object
#'
#' @family ListLocationsResponse functions
#' @export
ListLocationsResponse <- function(nextPageToken = NULL, locations = NULL) {
    structure(list(nextPageToken = nextPageToken, locations = locations), class = c("gar_ListLocationsResponse",
        "list"))
}

#' ReadWrite Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' Options for a transaction that can be used to read and write documents.
#'
#' @param retryTransaction An optional transaction to retry
#'
#' @return ReadWrite object
#'
#' @family ReadWrite functions
#' @export
ReadWrite <- function(retryTransaction = NULL) {
    structure(list(retryTransaction = retryTransaction), class = c("gar_ReadWrite",
        "list"))
}

#' GoogleFirestoreAdminV1ImportDocumentsRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for FirestoreAdmin.ImportDocuments.
#'
#' @param inputUriPrefix Location of the exported files
#' @param collectionIds Which collection ids to import
#'
#' @return GoogleFirestoreAdminV1ImportDocumentsRequest object
#'
#' @family GoogleFirestoreAdminV1ImportDocumentsRequest functions
#' @export
GoogleFirestoreAdminV1ImportDocumentsRequest <- function(inputUriPrefix = NULL, collectionIds = NULL) {
    structure(list(inputUriPrefix = inputUriPrefix, collectionIds = collectionIds),
        class = c("gar_GoogleFirestoreAdminV1ImportDocumentsRequest", "list"))
}

#' WriteResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for Firestore.Write.
#'
#' @param streamId The ID of the stream
#' @param streamToken A token that represents the position of this response in the stream
#' @param commitTime The time at which the commit occurred
#' @param writeResults The result of applying the writes
#'
#' @return WriteResponse object
#'
#' @family WriteResponse functions
#' @export
WriteResponse <- function(streamId = NULL, streamToken = NULL, commitTime = NULL,
    writeResults = NULL) {
    structure(list(streamId = streamId, streamToken = streamToken, commitTime = commitTime,
        writeResults = writeResults), class = c("gar_WriteResponse", "list"))
}

#' Value Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A message that can hold any of the supported value types.
#'
#' @param doubleValue A double value
#' @param geoPointValue A geo point value representing a point on the surface of Earth
#' @param arrayValue An array value
#' @param integerValue An integer value
#' @param nullValue A null value
#' @param bytesValue A bytes value
#' @param booleanValue A boolean value
#' @param timestampValue A timestamp value
#' @param mapValue A map value
#' @param stringValue A string value
#' @param referenceValue A reference to a document
#'
#' @return Value object
#'
#' @family Value functions
#' @export
Value <- function(doubleValue = NULL, geoPointValue = NULL, arrayValue = NULL, integerValue = NULL,
    nullValue = NULL, bytesValue = NULL, booleanValue = NULL, timestampValue = NULL,
    mapValue = NULL, stringValue = NULL, referenceValue = NULL) {
    structure(list(doubleValue = doubleValue, geoPointValue = geoPointValue, arrayValue = arrayValue,
        integerValue = integerValue, nullValue = nullValue, bytesValue = bytesValue,
        booleanValue = booleanValue, timestampValue = timestampValue, mapValue = mapValue,
        stringValue = stringValue, referenceValue = referenceValue), class = c("gar_Value",
        "list"))
}

#' DocumentDelete Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A Document has been deleted. May be the result of multiple writes, including updates, the last of which deleted the Document. Multiple DocumentDelete messages may be returned for the same logical delete, if multiple targets are affected.
#'
#' @param readTime The read timestamp at which the delete was observed
#' @param removedTargetIds A set of target IDs for targets that previously matched this entity
#' @param document The resource name of the Document that was deleted
#'
#' @return DocumentDelete object
#'
#' @family DocumentDelete functions
#' @export
DocumentDelete <- function(readTime = NULL, removedTargetIds = NULL, document = NULL) {
    structure(list(readTime = readTime, removedTargetIds = removedTargetIds, document = document),
        class = c("gar_DocumentDelete", "list"))
}

#' BeginTransactionResponse Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The response for Firestore.BeginTransaction.
#'
#' @param transaction The transaction that was started
#'
#' @return BeginTransactionResponse object
#'
#' @family BeginTransactionResponse functions
#' @export
BeginTransactionResponse <- function(transaction = NULL) {
    structure(list(transaction = transaction), class = c("gar_BeginTransactionResponse",
        "list"))
}

#' PartitionQueryRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.PartitionQuery.
#'
#' @param partitionCount The desired maximum number of partition points
#' @param pageSize The maximum number of partitions to return in this call, subject to `partition_count`
#' @param pageToken The `next_page_token` value returned from a previous call to PartitionQuery that may be used to get an additional set of results
#' @param structuredQuery A structured query
#'
#' @return PartitionQueryRequest object
#'
#' @family PartitionQueryRequest functions
#' @export
PartitionQueryRequest <- function(partitionCount = NULL, pageSize = NULL, pageToken = NULL,
    structuredQuery = NULL) {
    structure(list(partitionCount = partitionCount, pageSize = pageSize, pageToken = pageToken,
        structuredQuery = structuredQuery), class = c("gar_PartitionQueryRequest",
        "list"))
}

#' BatchWriteRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.BatchWrite.
#'
#' @param labels Labels associated with this batch write
#' @param writes The writes to apply
#'
#' @return BatchWriteRequest object
#'
#' @family BatchWriteRequest functions
#' @export
BatchWriteRequest <- function(labels = NULL, writes = NULL) {
  structure(list(labels = labels, writes = writes),
            class = c("gar_BatchWriteRequest", "list"))
}

#' RunQueryRequest Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' The request for Firestore.RunQuery.
#'
#' @param structuredQuery A structured query
#' @param transaction Reads documents in a transaction
#' @param readTime Reads documents as they were at the given time
#' @param newTransaction Starts a new transaction and reads the documents
#'
#' @return RunQueryRequest object
#'
#' @family RunQueryRequest functions
#' @export
RunQueryRequest <- function(structuredQuery = NULL, transaction = NULL, readTime = NULL,
    newTransaction = NULL) {
    structure(list(structuredQuery = structuredQuery, transaction = transaction,
        readTime = readTime, newTransaction = newTransaction), class = c("gar_RunQueryRequest",
        "list"))
}

#' DocumentTransform Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' A transformation of a document.
#'
#' @param fieldTransforms The list of transformations to apply to the fields of the document, in order
#' @param document The name of the document to transform
#'
#' @return DocumentTransform object
#'
#' @family DocumentTransform functions
#' @export
DocumentTransform <- function(fieldTransforms = NULL, document = NULL) {
    structure(list(fieldTransforms = fieldTransforms, document = document), class = c("gar_DocumentTransform",
        "list"))
}

#' GoogleLongrunningOperation Object
#'
#' @details
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' This resource represents a long-running operation that is the result of a network API call.
#'
#' @param metadata Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.
#' @param response The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.
#' @param done If the value is `false`, it means the operation is still in progress
#' @param error The error result of the operation in case of failure or cancellation
#' @param name The server-assigned name, which is only unique within the same service that originally returns it
#'
#' @return GoogleLongrunningOperation object
#'
#' @family GoogleLongrunningOperation functions
#' @export
GoogleLongrunningOperation <- function(metadata = NULL, response = NULL,
                                       done = NULL, error = NULL, name = NULL) {
    structure(list(
        metadata = metadata, response = response, done = done, error = error, name = name),
        class = c("gar_GoogleLongrunningOperation", "list"))
}

